export const GET_COUNTRIES = 'GET_COUNTRIES';
export const FILTER_COUNTRIES_BY_CONTINENT = 'FILTER_COUNTRIES_BY_CONTINENT';
export const GET_TOURIST_ACTIVITIES = 'GET_TOURIST_ACTIVITIES';
export const FILTER_BY_ACTIVITIES = 'FILTER_BY_ACTIVITIES';
export const ORDER_ALPHABETICALLY_BY_NAME = 'ORDER_ALPHABETICALLY_BY_NAME';
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME';




